/*	Problem 44 - Pentagon numbers:
	Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
	
	The first ten pentagonal numbers are:
	1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
	
	It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
	
	However, their difference, 70 − 22 = 48, is not pentagonal.
	
	Find the pair of pentagonal numbers, Pj and Pk, 
	for which their sum and difference are pentagonal 
	and D = |Pk − Pj| is minimised; what is the value of D?
*/

package euler;

public class projectEuler {
	public static void main (String [] args) {
		
		long time = System.nanoTime();
		
		int d = findMinDiff();
		System.out.println("\nThe answer is: "+d);
		
		time = System.nanoTime() - time;
		System.out.println("\nIt took "+(time/1000000)+"ms to execute");
	}
	
	public static int findMinDiff () {
		//note: because the diffrence between every 2 pentagonals is only getting bigger as n getting bigger
		//the first solution we find is also the smallest
		int i = 0;
		while(true) {
			i++;
			for(int j = 1; j < i; j++) {
				//check if the sum and diff are both Pentagon numbers
				int n1 = i*(3*i - 1)/2;
				int n2 = j*(3*j - 1)/2;
				if(isPentagonal(n1+n2))
					if(isPentagonal(n1 - n2))
						return (n1-n2);
			}
		}
	}
	
	public static boolean isPentagonal(int n) {
		//if we take the function Pn=n(3n−1)/2 and use its inverse
		//(Math,sqrt(24x+1) + 1)/6, and check for integer solution
		double x = (Math.sqrt(24*n + 1) + 1)/6;
		return (x == (int)x);
	}
	
}
